### ISSUE TITLE
Remove `react/no-array-index-key`

### ISSUE THREAD

**Issue by edizcelik** [Hipo/eslint-config-hipo-react#15]
What do you think about removing this rule?
cc: @burakguneli @mucahit @bilgeyucel

**Comment by bilgeyucel** [comment]
I think this rule is necessary. Just recently I had a problem because of the lack of this rule. Why do you want to remove it @edizcelik?

**Comment by bilgeyucel** [comment]
We decided to use it as `warning` instead of `error`
