### ISSUE TITLE
Add `react-hooks/exhaustive-deps` Rule

### ISSUE THREAD

**Issue by mucahit** [Hipo/eslint-config-hipo-react#16]
To avoid possible infinite `useEffect` loops, we can add `react-hooks/exhaustive-deps` rule. [Details &raquo;](https://www.npmjs.com/package/eslint-plugin-react-hooks)

**Comment by edizcelik** [comment]
`eslint-plugin-react-hooks` handles these and they are added with the template. I think we can include that plugin here and add the following rules:

```
    "react-hooks/rules-of-hooks": 2,
    "react-hooks/exhaustive-deps": 1,
```
