### ISSUE TITLE
Force devs to use proptypes if typescript is not being used in the project

### ISSUE THREAD

**Issue by bedirhankaradogan** [Hipo/eslint-config-hipo-react#6]

**Comment by edizcelik** [comment]
I don't think this can be done here but should be added to individual projects as custom config. Or we can export separate rules for `typescript` and `javascript` projects. For instance, `Hipo/eslint-config-hipo-base` exports different rules for es5 and es6.

**Comment by bilgeyucel** [comment]
I will remove `react/prop-types` rule but add a warning to README so that JS users should add this rule to their config.
